### ISSUE TITLE
utils scope

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#124]
The scope of utils is getting too big.  I suggest we break it up into themed submodules.  For example, make utils a directory and have time, coords, stats, et cetera.

**Comment by rstoneback** [comment]
See related issue #114

**Comment by jklenzing** [comment]
Revisiting this as I work on unit tests for the coords.py file.  Breaking utils into four subsets, which we can refine later.  These are:
- coords (352 lines)
- stats (116 lines)
- time (286 lines)
- misc (491 lines)

The misc set basically has four functions (including the load_netcdf4, which takes up most of the space).

**Comment by jklenzing** [comment]
Likewise, how should we organize the unit tests?  We could simply have a `test_utils.py` file with a different class for each submodule.

**Comment by aburrell** [comment]
I propose a bit of a structural change.  Let's create a utils directory and place coords, stats, time, file, and misc (what's left there besides file utilities?) in this directory.  Then we'd be importing pysat.utils.coords, which maintains the intent behind each of these and won't bloat the top level directory as we add more functionality.

I also say we incorporate ssnl into stats.  Conceptually, I'd expect to encounter the seasonal implementations under pysat.utils.stats.ssnl.  Also, they aren't so much seasonal as long-term and a name change _might_ be appropriate.  Finally, the "invisible" routines in ssnl should be accessable in stats.  In my opinion.

However, the current testing idea says any time you have a file, it gets its own test file.  You can have classes within that file, however.  So, for example, all coords routines are tested in test_coords.  But there is one class that deals with all of the radar-related routines, another that deals with rocket-related routines, and so on.

**Comment by jklenzing** [comment]
@aburrell, I've pushed my current changes to #144.  Not a working build yet, but it will be useful for structural comments.  `misc` contains `computational_form`, `set_data_dir`, `load_netcdf4`, and `scale_units`.

**Comment by aburrell** [comment]
Thoughts:

* set_data_dir will need to still exist at the .utils level.  Perhaps we have a utils.py file in the utils directory and all the routines there are imported one level up.
* scale_units could be place in coords, since it allows coordinate transformation between, for example, km and m.
* @rstoneback needs to comment on computational_form, after reading the docstring I don't really know when I should use it

**Comment by jklenzing** [comment]
Two more candidates for misc:
- adjust_cyclic_data
- update_longitude

I accidentally copied these over with the time functions last round.  Not sure where they should go, or if they should be their own thing (space?)

**Comment by aburrell** [comment]
Longitude is a coordinate, so I'd put it in coords.  Cyclic could go there, too, I suppose.

**Comment by jklenzing** [comment]
Cyclic adjusts coordinates such as longitude, so I agree.

**Comment by jklenzing** [comment]
Current line count:
- coords - 491
- misc - 377
- stats - 115
- time - 221
- utils - 35

Note that we still haven't added pysatMagVect as outlined in #114.  Going to continue along this path for now, but noting that coords may need to be further broken up.

**Comment by jklenzing** [comment]
Also, thanks to whoever wrote unit tests for utils.py.  It's definitely helping me track down what needs to be changed as I move functions around.

**Comment by rstoneback** [comment]
I started test_utils and Angeline extended it. You are welcome :)

* @rstoneback needs to comment on computational_form, after reading the docstring I don't really know when I should use it
     OK. In the seasonal averaging code I need to support multiple data formats, Series, DataFrames, and a series of Frames. Each of these formats requires some different ops to say, perform a mean, median, etc. Computational form will take any of the expected data formats and returns them in a config such that no matter the initial input, you can perform calcs using the same code. If out is returned, then out.mean() gives an appropriate mean.

I don't think I got around to actually using this method within the seasonal averging (doh!), but it is used in the _core_mean method within pysat.ssnl.avg

**Comment by rstoneback** [comment]
> Thoughts:
> 
> * set_data_dir will need to still exist at the .utils level.  Perhaps we have a utils.py file in the utils directory and all the routines there are imported one level up.

Agreed. In instances like this I'll call the underlying routine _core.py or something with an underscore. This way you avoid having to call pysat.utils.utils.stuff. Things in the _core.py will have to be imported into pysat.utils in the utils/init.py.

**Comment by rstoneback** [comment]
> 
> However, the current testing idea says any time you have a file, it gets its own test file. You can have classes within that file, however. So, for example, all coords routines are tested in test_coords. But there is one class that deals with all of the radar-related routines, another that deals with rocket-related routines, and so on.

We may want to consider this plan for the future. Some of the test_* files are getting pretty long, makes it hard to see what is going on. An alternative is to break up the file for test_coords by some grouping, and then label along the lines of, test_coords_blah.py

**Comment by jklenzing** [comment]
Trying to merge the latest updates from develop was a bit of a nightmare, so I've closed the coordinate pull request and will start from a fresh branch.  I may wait on this until a couple more pull requests get sorted out and merged.  I've got a good set of notes to compare, so this shouldn't be too much to get it back up and running.

**Comment by jklenzing** [comment]
> > However, the current testing idea says any time you have a file, it gets its own test file. You can have classes within that file, however. So, for example, all coords routines are tested in test_coords. But there is one class that deals with all of the radar-related routines, another that deals with rocket-related routines, and so on.
> 
> We may want to consider this plan for the future. Some of the test_* files are getting pretty long, makes it hard to see what is going on. An alternative is to break up the file for test_coords by some grouping, and then label along the lines of, test_coords_blah.py

I like the idea of breaking up the unit tests a little more by function.  Particularly in something like utils, where a lot of things get called in setup and teardown but are not necessarily used in every test.

**Comment by rstoneback** [comment]
The test files reveal their evolutionary development. Only actively harmful statements are selected against. :)

**Comment by jklenzing** [comment]
Moving `load_netcdf4` and `computational_form` to `_core.py`.  I think this make more sense with the flow of the tests.

**Comment by jklenzing** [comment]
This one is in the queue.  Going to wait until after the pycodestyle merge to put in the request.  May need a few more unit tests.

**Comment by jklenzing** [comment]
Closed with merge of #164.
